[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0

[program:nginx]
command=nginx -g "daemon off;"
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stdout

[program:main]
command=java -jar /app/backend-main.jar
environment=SPRING_DATASOURCE_URL="jdbc:sqlite:/app/data/taffy.db"
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stdout

[program:voice]
command=java -jar /app/backend-voice-ai.jar
environment=SPRING_DATASOURCE_URL="jdbc:sqlite:/app/data/taffy.db",VOICE_AI_STORAGE_ROOT="/app/data/audio"
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stdout

[program:extra]
command=java -jar /app/backend-extended.jar
environment=SPRING_DATASOURCE_URL="jdbc:sqlite:/app/data/taffy.db"
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stdout
